stand_task_config_dir = {
    "20news":
        {"epochs": "1", "lr": "5e-3", "wd": "0.0001",
         "lstm_dropout": "0.1",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.0",
         "do_remove_stop_words": "True", "do_remove_low_freq_words": "5",
         "batch_size": "32", "max_seq_len": "200",
         "comm_round": "200", "num_filter": "50", "cnn_dropout": "0.1"},
    "agnews":
        {"epochs": "1", "lr": "5e-3", "wd": "0.0001",
         "lstm_dropout": "0.1",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.0",
         "do_remove_stop_words": "True", "do_remove_low_freq_words": "0",
         "batch_size": "256", "max_seq_len": "128",
         "comm_round": "200", "num_filter": "50", "cnn_dropout": "0.1"},
    "sst_2":
        {"epochs": "1", "lr": "5e-3", "wd": "0.0001",
         "lstm_dropout": "0.5",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.3",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "0",
         "batch_size": "400", "max_seq_len": "32",
         "comm_round": "200", "num_filter": "50", "cnn_dropout": "0.5"},
    "sentiment140":
        {"epochs": "1", "lr": "1e-3", "wd": "0.0005",
         "lstm_dropout": "0.5",
         "embedding_file": "glove.840B.300d.txt", "embedding_dropout": "0.3",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "5",
         "batch_size": "256", "max_seq_len": "32",
         "comm_round": "50", "num_filter": "50", "cnn_dropout": "0.5"},
    "finance":
        {"epochs": "20", "lr": "5e-3", "wd": "0.0001",
         "lstm_dropout": "0.1",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.0",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "0",
         "batch_size": "32", "max_seq_len": "32", "gpu": "0",
         "comm_round": "50", "ci": "1", "num_filter": "50", "cnn_dropout": "0.1"},
    "depression":
        {"epochs": "20", "lr": "1e-3", "wd": "0.0001",
         "lstm_dropout": "0.1",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.0",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "0",
         "batch_size": "32", "max_seq_len": "32", "gpu": "0",
         "comm_round": "50", "ci": "1", "num_filter": "50", "cnn_dropout": "0.1"},
}

tune_task_config_dir = {
    "20news":
        {"epochs": "10", "lr": "5e-3", "wd": "0.0001",
         "lstm_dropout": "0.5",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.0",
         "do_remove_stop_words": "True", "do_remove_low_freq_words": "5",
         "batch_size": "400", "max_seq_len": "512",
         "comm_round": "100", "ci": "1", "num_filter": "50", "cnn_dropout": "0.5"},
    "agnews":
        {"epochs": "10", "lr": "5e-3", "wd": "0.0001",
         "lstm_dropout": "0.1",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.0",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "0",
         "batch_size": "256", "max_seq_len": "128",
         "comm_round": "60", "ci": "1", "num_filter": "50", "cnn_dropout": "0.1"},
    "finance":
        {"epochs": "20", "lr": "5e-3", "wd": "0.0001",
         "lstm_dropout": "0.1",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.0",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "0",
         "batch_size": "64", "max_seq_len": "64", "gpu": "0",
         "comm_round": "100", "ci": "1", "num_filter": "50", "cnn_dropout": "0.7"},
    "depression":
        {"epochs": "20", "lr": "1e-3", "wd": "0.0001",
         "lstm_dropout": "0.1",
         "embedding_file": "glove.6B.300d.txt", "embedding_dropout": "0.0",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "0",
         "batch_size": "32", "max_seq_len": "32", "gpu": "0",
         "comm_round": "100", "ci": "1", "num_filter": "50", "cnn_dropout": "0.1"},
    "sst_2":
        {"epochs": "1", "lr": "5e-3", "wd": "0.0001",
         "lstm_dropout": "0.5",
         "embedding_file": "glove.840B.300d.txt", "embedding_dropout": "0.3",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "0",
         "batch_size": "400", "max_seq_len": "32",
         "comm_round": "150", "ci": "1", "num_filter": "50", "cnn_dropout": "0.5"},
    "sentiment140":
        {"epochs": "2", "lr": "1e-3", "wd": "0.0005",
         "lstm_dropout": "0.5",
         "embedding_file": "glove.840B.300d.txt", "embedding_dropout": "0.3",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "5",
         "batch_size": "256", "max_seq_len": "32",
         "comm_round": "50", "ci": "1", "num_filter": "50", "cnn_dropout": "0.5"},
}

tlm_task_config_dir = {
    "20news":
        {
            "distilbert": {"epochs": "2", "lr": "5e-5", "weight_decay": "0.0",
                           "train_batch_size": "64", "eval_batch_size": "64",
                           "max_seq_len": "256", "comm_round": "200"},
            "bert": {"epochs": "2", "lr": "5e-5", "weight_decay": "0.0",
                     "train_batch_size": "64", "eval_batch_size": "64",
                     "max_seq_len": "256", "comm_round": "200"},
            "albert": {"epochs": "2", "lr": "5e-5", "weight_decay": "0.0",
                       "train_batch_size": "64", "eval_batch_size": "64",
                       "max_seq_len": "256", "comm_round": "150"},
        },
    "agnews":
        {
            "albert": {"epochs": "2", "lr": "5e-5", "weight_decay": "0.0",
                       "train_batch_size": "128", "eval_batch_size": "128",
                       "max_seq_len": "128", "comm_round": "150", },
            "bert": {"epochs": "2", "lr": "5e-5", "weight_decay": "0.0",
                     "train_batch_size": "128", "eval_batch_size": "128",
                     "max_seq_len": "128", "comm_round": "150", },
            "distilbert": {"epochs": "2", "lr": "5e-5", "weight_decay": "0.0",
                           "train_batch_size": "128", "eval_batch_size": "128",
                           "max_seq_len": "128", "comm_round": "150"},
        },
    "sst_2":
        {
            "albert": {"epochs": "3", "lr": "5e-5", "weight_decay": "0.0",
                       "train_batch_size": "256", "eval_batch_size": "128",
                       "max_seq_len": "32", "comm_round": "100", },
            "bert": {"epochs": "3", "lr": "5e-5", "weight_decay": "0.0",
                     "train_batch_size": "256", "eval_batch_size": "200",
                     "max_seq_len": "32", "comm_round": "100", },
            "distilbert": {"epochs": "3", "lr": "5e-5", "weight_decay": "0.0",
                           "train_batch_size": "256", "eval_batch_size": "128",
                           "max_seq_len": "32", "comm_round": "100", },
        },
    "depression":
        {
            "albert": {"epochs": "1", "lr": "5e-5", "weight_decay": "0.0",
                       "train_batch_size": "256", "eval_batch_size": "128",
                       "max_seq_len": "32", "comm_round": "100", "ci": "1",
                       },
            "bert": {"epochs": "1", "lr": "5e-5", "weight_decay": "0.0",
                     "train_batch_size": "256", "eval_batch_size": "128",
                     "max_seq_len": "32", "comm_round": "100", "ci": "1",
                     },
            "distilbert": {"epochs": "1", "lr": "5e-5", "weight_decay": "0.0",
                           "train_batch_size": "256", "eval_batch_size": "128",
                           "max_seq_len": "32", "comm_round": "100", "ci": "1",
                           },
        },
    "finance":
        {
            "albert": {"epochs": "1", "lr": "2e-5", "weight_decay": "0.0",
                       "train_batch_size": "32", "eval_batch_size": "128",
                       "max_seq_len": "32", "comm_round": "100", "ci": "1",
                       },
            "bert": {"epochs": "1", "lr": "2e-5", "weight_decay": "0.0",
                     "train_batch_size": "32", "eval_batch_size": "128",
                     "max_seq_len": "64", "comm_round": "100", "ci": "1",
                     },
            "distilbert": {"epochs": "1", "lr": "2e-5", "weight_decay": "0.0",
                           "train_batch_size": "32", "eval_batch_size": "128",
                           "max_seq_len": "64", "comm_round": "100", "ci": "1",
                           },
        },
    "sentiment140":
        {"epochs": "2", "lr": "1e-3", "wd": "0.0005",
         "lstm_dropout": "0.5",
         "embedding_file": "glove.840B.300d.txt", "embedding_dropout": "0.3",
         "do_remove_stop_words": "False", "do_remove_low_freq_words": "5",
         "batch_size": "256", "max_seq_len": "32",
         "comm_round": "50", "ci": "1", "num_filter": "50", "cnn_dropout": "0.5"},
}
